name: portfolio
description: A portfolio made using flutter

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.3.2
  http: ^0.12.0+2
  url_launcher: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/works/
  fonts:
    - family: GoogleSansRegular
      fonts:
        - asset: assets/GoogleSansRegular.ttf
